# Generated by Django 4.1.5 on 2023-02-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_rename_question_text_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='question_id',
        ),
    ]
