# Generated by Django 4.1.5 on 2023-02-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_rename_question_id_option_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_text',
            new_name='option',
        ),
    ]
